package router

import (
	"neneloga/internal/handlers"
	"neneloga/internal/middleware"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "neneloga/docs" // generated by swaggo
)

func SetupRouter() *gin.Engine {
	r := gin.Default()

	// CORS config
	config := cors.DefaultConfig()
	config.AllowAllOrigins = true
	config.AllowCredentials = true
	config.AddAllowHeaders("Authorization")
	r.Use(cors.New(config))

	// ── Public routes ──────────────────────────────────────────────────────
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.GET("/", handlers.Home)
	r.GET("/health", handlers.Health)
	r.GET("/chuck", handlers.ChuckNorris)

	// Auth routes (no token required)
	r.POST("/signup", handlers.Signup)
	r.POST("/login", handlers.Login)
	r.POST("/logout", handlers.Logout)
	r.POST("/refresh", handlers.Refresh)

	// ── Protected routes (JWT required) ────────────────────────────────────
	auth := r.Group("/v1")
	auth.Use(middleware.RequireAuth())
	{
		// Current user profile
		auth.GET("/me", handlers.Me)

		// Users CRUD
		users := auth.Group("/users")
		{
			users.GET("/", handlers.GetUsers)
			users.POST("/", handlers.CreateUser)
			users.GET("/:id", handlers.GetUser)
			users.PUT("/:id", handlers.UpdateUser)
			users.DELETE("/:id", handlers.DeleteUser)
		}

		// Servers CRUD
		serverHandler := handlers.NewServerHandler()
		servers := auth.Group("/servers")
		{
			servers.GET("", serverHandler.GetServers)
			servers.POST("", serverHandler.CreateServer)
			servers.GET("/:id", serverHandler.GetServer)
			servers.PUT("/:id", serverHandler.UpdateServer)
			servers.DELETE("/:id", serverHandler.DeleteServer)
		}
	}

	r.NoRoute(handlers.NotFound)

	return r
}
