package router

import (
	"neneloga/internal/handlers"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "neneloga/docs" // This will be generated by swaggo
)

func SetupRouter() *gin.Engine {
	r := gin.Default()

	// Swagger route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.GET("/",handlers.Home)

	// health
	r.GET("/health", handlers.Health)

	r.GET("/chuck",handlers.ChuckNorris)

	// r.GET("/users")

	// r.GET("/ping", handlers.Ping)

	user := r.Group("/users")
	{
	    user.GET("/", handlers.GetUsers)
		user.GET("/:id", handlers.GetUser)
	    user.POST("/", handlers.CreateUser)
		user.PUT("/:id", handlers.UpdateUser)
		user.DELETE("/:id", handlers.DeleteUser)
	}

	r.NoRoute(handlers.NotFound)

	return r
}
